### ISSUE TITLE
Not an issue more like asking for help

### ISSUE THREAD

**Issue by Yassine3isi** [JustNao/Karrelage#1]
I don't know why i keep getting this error when trying to update the protocole
![image](https://user-images.githubusercontent.com/116572296/232194469-a644cfcf-7053-47a8-a235-633b33b64a6b.png)

**Comment by JustNao** [comment]
The regex used to find the type of each element in the protocols fails somewhere. I can't reproduce on my side with the latest update, can you try to completely delete the protocols folder and decompile again ? May have been an issue with your decompiling creating a corrupted file or something.

**Comment by Yassine3isi** [comment]
Dans la décompilation je reçois ce message , 
![image](https://user-images.githubusercontent.com/116572296/232228491-7868aeda-a2c7-4096-bc0d-0435f61a50a9.png)
apres quel version python et ffdec tu utilise ?
python 3.11 et ffdec 18.4.0

**Comment by JustNao** [comment]
L'erreur est "normale", je l'ai aussi en décompilant. Elle ne produit pas de fichiers corrompus, ignore la juste jusqu'à ce que tous les script soient exportés, puis tu peux cliquer sur "OK". Tu peux lancer ffdec par le .bat et pas le .exe, ça a l'air d'enlever l'erreur. Je viens d'ajouter un script `script/update_packets.py` pour faire tout en même temps (qui utilise le .bat), vois si tu as toujours l'erreur avec ça.

**Comment by Yassine3isi** [comment]
Encore le meme problem , la decompilation se passe bien mais au moment du build protocole.pk sa passe pas 
![image](https://user-images.githubusercontent.com/116572296/232230554-df585120-3945-4173-ae14-c8d591093681.png)
Est ce que ton dossier protocole est comme le mien : 
![image](https://user-images.githubusercontent.com/116572296/232230580-48460f48-3877-4831-aefa-17d3096e6afa.png)

**Comment by JustNao** [comment]
Il y'avait une erreur sur `update_packets.py`, il ne prenait pas les bons fichiers sources pour build protocol.pk. Supprime tous tes dossiers `protocol` et ré-essaye. Si ça ne marche toujours pas, tu peux essayer de debug en regardant quel fichier en particulier pose problème, voir ce qu'il a de différent.

**Comment by JustNao** [comment]
The issue was coming from the ffdec decompiler version, which doesn't have the same output for certain classes. Version [14.6.0](https://github.com/jindrapetrik/jpexs-decompiler/releases/tag/version14.6.0) works (I didn't try which version specifically broke it).
