### ISSUE TITLE
[Question] Y'a un support pour l'écriture/envoie de packet vers le serveur?

### ISSUE THREAD

**Issue by Phaired** [JustNao/Karrelage#11]
Si oui j'aimerai bien savoir où car je suis pas sûr que la méthode write dans protocol.py le fasse x)

**Comment by JustNao** [comment]
Il y'a en effet un support par le biais de [LaBot ](https://github.com/louisabraham/LaBot), qui est utilisé pour la lecture/écritue des packets.
La méthode [write de procotol.py](https://github.com/JustNao/Karrelage/blob/737daa5a857c6ba6fe26e2d7929227355851e462/src/sniffer/protocol.py#L103) est bien utilisée pour convertir un type+dict en bytes. C'est cependant uniquement appliqué en mode "attach" de Karrelage (comme le sniffer ne fait que lire les packets entrant).
Tu as un exemple de classe qui fait juste du forwarding de packets [ici](https://github.com/JustNao/Karrelage/blob/737daa5a857c6ba6fe26e2d7929227355851e462/src/mitm/bridge.py#L147).
