### ISSUE TITLE
Issue with AutoSwitch and AutoPass

### ISSUE THREAD

**Issue by pedrinhodosus** [JustNao/Karrelage#7]
Hello bro, I did everything, the app opens, the Team Manager too, he can sniff the combat infos but dont switch to the character window and dont pass the turn in the others, could you help please?

Oh another thing, I installed playsound 1.2.2 to work, because the newest version simply doesnt install in my PC

**Comment by pedrinhodosus** [comment]
ok, now its working, I uncomment the section to switch the screen and the autopass its working fine with my hotkey to pass, but I have a problem bro, when one new battle start the module updates and uncheck the AutoTurn box, theres a way to make it be marked forever? I mean, even when the fight ends and start another one the box keeps marked.

**Comment by JustNao** [comment]
Yeah I see the issue, don't know how I missed it when implementing the auto turn. I clear the teams every new combat, but I don't store the auto_turn. Either we store that config by player ID, which resets at every connection, or we store the player name. Either way, should be an easy fix, will work on it this weekend.

**Comment by pedrinhodosus** [comment]
well, I did it with 
`    def handle_GameFightEndMessage(self, _):
        """Triggered when the fight ends."""

        self.fighting = True`

in team_manager.py
so the fight state will never be cleared and keeps the state forever xD

But its only for personal use so maybe theres a better whay to do it.

Another thing, do you know how to change the game icon for every different window? like Organizer does
